CREATE TABLE IF NOT EXISTS `lab_pet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `netID` int(11) DEFAULT NULL,
  `petHash` varchar(50) DEFAULT NULL,
  `petTexureID` int(11) DEFAULT NULL,
  `petLeash` varchar(50) DEFAULT NULL,
  `petLeashID` int(11) DEFAULT NULL,
  `petOwner` varchar(50) DEFAULT NULL,
  `petGender` varchar(50) DEFAULT NULL,
  `petName` varchar(50) DEFAULT NULL,
  `petLabel` longtext DEFAULT NULL,
  `hungryDecrase` int(11) DEFAULT NULL,
  `petHungryLevel` int(11) DEFAULT NULL,
  `thirstDecrase` int(11) DEFAULT NULL,
  `isOutSide` tinyint(4) DEFAULT 0,
  `petThirstLevel` int(11) DEFAULT NULL,
  `petEnergyLevel` int(11) DEFAULT NULL,
  `petHealthLevel` int(11) DEFAULT NULL,
  `petXP` int(11) DEFAULT NULL,
  `lastXP` int(11) DEFAULT NULL,
  `petLevel` int(11) DEFAULT NULL,
  `petPosition` text DEFAULT NULL,
  `petIMG` longtext DEFAULT 'unkownpet.png',
  `listOf` varchar(50) DEFAULT NULL,
  `isSelling` tinyint(4) DEFAULT 0,
  `petSellingPrice` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `netID` (`netID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;