Config = {     --- If you have a suggestions on new skills, contact us on discord and tag @burbonas
    Mysql = "oxmysql",
    KeyToOpenSkillMenu = 161, --(number 7 right now)    --https://docs.fivem.net/docs/game-references/controls/
   
    LevelingDifficulty = 50,--%  the difficulty to level up in [ % ]  
    SkillPointsPerLevel = 1, -- how many skill points player will get EACH LEVEL UP

    LevelupEffect = false, --  Should the "levelup" effect that appears on your character when you level up be on or not?
    LevelUPEffect_dictName ="scr_indep_fireworks" , -- https://vespura.com/fivem/particle-list/
    LevelUPEffect_particlename = "scr_indep_firework_shotburst",  --https://vespura.com/fivem/particle-list/

    
    TimerEarnXP = true, -- Whether the player gains xp over time while in the game or not?
    TimerEarnXP_Time = 100000, --+100000, -- how many seconds to gain xp (msec)
    TimerEarnXP_Amount = 10, -- how many seconds to gain xp

    -- Camera Side
    HeightRecognizedAsInterior = -10, -- Most shells (interiors generated by scripts) are below ground. Set height which is defined as interior
    StartFOV = 60.0,
    EndFOV = 20.0,

    CameraOffsetStart = vector3(0.0, 0.8, 0.0),
    CameraOffsetEnd = vector3(0.0, 6.0, 0.0), -- Offset from player while camera active
    CameraTransitionTime = 400, -- Time in miliseconds it takes to transition from start to end offsets

    CameraVehicleOffsetStart = vector3(-1.0,10.0,1.0),
    CameraVehicleOffsetEnd = vector3(-8.0, 0.0, 1.5), -- Offset from player vehicle while camera active
    VehicleCameraTransitionTime = 700, -- Time in miliseconds it takes to transition from start to end offsets

    CameraTrunkOffsetStart = vector3(-0.1,0.1,3.0),
    CameraTrunkOffsetEnd = vector3(-5.0, 1.0, 3.0), -- Offset from player using trunk while camera active
    TrunkCameraTransitionTime = 700, -- Time in miliseconds it takes to transition from start to end offsets

    -- XP kazanırken Zamanlamı kazansın yoksa eventlemi o ypaılacak 
    -- 100XP 1 Level olmak şartı gelecek
    -- 1Level atlayınca kaç point kazanacağı yazacak
    -- Script'in yazım şeklini değiştirmek gerekiyor.

    Skills = { 
        {
            skill = "StarterSkill",
            skillName = "Starter Skill",
            skillDescription = "When you unlock this skill, your stamina will decrease by 5.5%.",
            skillPoint = 0,
            skillGif = "https://cdn.discordapp.com/attachments/937806670434795560/937814995662692362/ezgif-7-cf86930ba5.gif",
            BeforeOpenSkill = "",
            AfterOpenSkills = "HealthSkill1",
            AfterOpenSkills2 = "StaminaSkill1",
            SkillEffects = {},
            marginTop = 20, -- in Nui Coords (%)
            marginLeft = 2, -- in Nui Coords (%)
            iconName = "starterskill",
        },
        
        -- Health side
        {
            skill = "HealthSkill1",
            skillName = "The Healer: Chapter1",
            skillDescription = "When you get this skill, you can heal faster and gain +10 health points.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355798318067712/health.gif",
            BeforeOpenSkill = "StarterSkill",
            AfterOpenSkills = "HealthSkill2",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_HealthRegens = { 
                    RegenerationSpeed = 5, 
                    Start_Regeneration = 20, 
                    Stop_Regeneration = 40, 
                },
                A_Health = 10,
            },
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 8, -- in Nui Coords (%)
            iconName = "healthskills1",
        },
        {
            skill = "HealthSkill2",
            skillName = "The Healer: Chapter2",
            skillDescription = "When you get this skill, you can heal faster and gain +20 health points.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355798318067712/health.gif",
            BeforeOpenSkill = "HealthSkill1",
            AfterOpenSkills = "HealthSkill3",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_HealthRegens = { 
                    RegenerationSpeed = 8, 
                    Start_Regeneration = 20, 
                    Stop_Regeneration = 40, 
                },
                A_Health = 20,
            },
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 16, -- in Nui Coords (%)
            iconName = "healthskills2",
            
        },

        -- ** Health Regen
        {
            skill = "HealthSkill3",
            skillName = "The Healer: Chapter3",
            skillDescription = "When you get this skill, you can heal faster and gain +30 health points and when you run, you get 5% less tired",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355798318067712/health.gif",
            BeforeOpenSkill = "HealthSkill2",
            AfterOpenSkills = "HealthSkill4",
            AfterOpenSkills2 = "",
            SkillEffects = { 
                A_SprintSt = 5,
                A_Health = 30,

            },
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 23, -- in Nui Coords (%)
            iconName = "healthregen",  
        },
        {
            skill = "HealthSkill4",
            skillName = "The Healer: Chapter4",
            skillDescription = "When you get this skill, you can heal faster",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355798318067712/health.gif",
            BeforeOpenSkill = "HealthSkill3",
            AfterOpenSkills = "HealthSkill5",
            AfterOpenSkills2 = "ArmorSkill1",
            SkillEffects = {
                -- A_SprintSt = 5,s
                A_HealthRegens = { 
                    RegenerationSpeed = 9, 
                    Start_Regeneration = 20, 
                    Stop_Regeneration = 40, 
                },
                -- A_Health = 50,

            },
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 29, -- in Nui Coords (%)
            iconName = "healthregen",  
        },
        {
            skill = "HealthSkill5",
            skillName = "The Healer: Chapter5 (Renewal)",
            skillDescription = "When you get this skill, you can heal faster and gain +50 health points and when you run, you get 10% less tired",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355798318067712/health.gif",
            BeforeOpenSkill = "HealthSkill4",
            AfterOpenSkills = "HealthSkill6",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_HealthRegens = { 
                    RegenerationSpeed = 10, 
                    Start_Regeneration = 20, 
                    Stop_Regeneration = 40, 
                },
                A_Health = 50,
            },
            marginTop = 8, -- in Nui Coords (%)
            marginLeft = 29, -- in Nui Coords (%)
            iconName = "healthregen",  
        },
        {
            skill = "HealthSkill6",
            skillName = "The Healer: Chapter6 (Renewal)",
            skillDescription = "Last level upgrade and quickly regenerate your stamina at 25% and your health at 50%, with a regeneration rate of 40%.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355798318067712/health.gif",
            BeforeOpenSkill = "HealthSkill5",
            AfterOpenSkills = "",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_HealthRegens = { 
                    RegenerationSpeed = 10, 
                    Start_Regeneration = 20, 
                    Stop_Regeneration = 40, 
                },
            },
            marginTop = 8, -- in Nui Coords (%)
            marginLeft = 37, -- in Nui Coords (%)
            iconName = "healthregen",  
        },

        -- ** Armor Regeneration
        {
            skill = "ArmorSkill1",
            skillName = "One Guard : Chapter1",
            skillDescription = "Adds 10+ to your armor",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354835821764688/armorgif.gif",
            BeforeOpenSkill = "HealthSkill4",
            AfterOpenSkills = "ArmorSkill2",
            AfterOpenSkills2 = "",
            SkillEffects = { A_Armor = 10},
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 37, -- in Nui Coords (%)
            iconName = "armorregen",  
        },

        {
            skill = "ArmorSkill2",
            skillName = "One Guard : Chapter2",
            skillDescription = "Adds 20+ to your Armor and refills it 10% faster.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354835821764688/armorgif.gif",
            BeforeOpenSkill = "ArmorSkill1",
            AfterOpenSkills = "ArmorSkill3",
            AfterOpenSkills2 = "",
            SkillEffects = { A_Armor = 20},
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 44, -- in Nui Coords (%)
            iconName = "armorregen",  
        },
        {
            skill = "ArmorSkill3",
            skillName = "One Guard : Chapter3",
            skillDescription = "Adds 30+ to your Armor and refills it 16% faster.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354835821764688/armorgif.gif",
            BeforeOpenSkill = "ArmorSkill2",
            AfterOpenSkills = "ArmorSkill4",
            AfterOpenSkills2 = "",
            SkillEffects = {  A_Armor = 30 },
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 50, -- in Nui Coords (%)
            iconName = "armorregen",  
        },
        {
            skill = "ArmorSkill4",
            skillName = "One Guard : Chapter4",
            skillDescription = "Adds 50+ to your Armor and refills it 16% faster.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354835821764688/armorgif.gif",
            BeforeOpenSkill = "ArmorSkill3",
            AfterOpenSkills = "ArmorSkill5",
            AfterOpenSkills2 = "",
            SkillEffects = { A_Armor = 50 },
            marginTop = 14, -- in Nui Coords (%)
            marginLeft = 57, -- in Nui Coords (%)
            iconName = "armorregen",  
        },

        -- -- Stamina side
        {
            skill = "StaminaSkill1",
            skillName = "The Flash : Chapter1",
            skillDescription = "You save 3% of the stamina you spend while running and 5% less, so you can get faster and longer runs.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040315943429095504/ezgif.com-gif-maker_1.gif",
            BeforeOpenSkill = "StarterSkill",
            AfterOpenSkills = "StaminaSkill2",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_SprintSt = 5,
                A_StaminaSaving = 3
            },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 8, -- in Nui Coords (%)
            iconName = "staminaskills1",
            
        },
        {
            skill = "StaminaSkill2",
            skillName = "The Flash : Chapter2",
            skillDescription = "When you run 1.05 (low +) faster, you maintain 8% of your endurance",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040315943429095504/ezgif.com-gif-maker_1.gif",
            BeforeOpenSkill = "StaminaSkill1",
            AfterOpenSkills = "StaminaSkill3",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_Speed = 1.05,
                A_SprintSt = 8,
            },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 16, -- in Nui Coords (%)
            iconName = "staminaskills2",  
        },
        {
            skill = "StaminaSkill3",
            skillName = "The Flash : Chapter4",
            skillDescription = "When you run 1.15 (medium +) faster, you maintain 20% of your endurance",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040315943429095504/ezgif.com-gif-maker_1.gif",
            BeforeOpenSkill = "StaminaSkill2",
            AfterOpenSkills = "StaminaSkill4",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_SprintSt = 20,
                A_Speed = 1.15,

            },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 23, -- in Nui Coords (%)
            iconName = "staminaskills2",  
        },
        {
            skill = "StaminaSkill4",
            skillName = "The Flash : Chapter4",
            skillDescription = "When you run 1.30 (high +) faster, you keep 20% of your stamina, spend it while running and use 20% less",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040315943429095504/ezgif.com-gif-maker_1.gif",
            BeforeOpenSkill = "StaminaSkill3",
            AfterOpenSkills = "SwimingSkill1",
            AfterOpenSkills2 = "",
            SkillEffects = {
                A_StaminaSaving = 10,
                A_Speed = 1.30,
                A_SprintSt = 20,
            },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 31, -- in Nui Coords (%)
            iconName = "staminaskills2",  
        },


        -- Swiming 
        {
            skill = "SwimingSkill1",
            skillName = "Aquaman : Chapter1",
            skillDescription = "Swim 1.05% faster on water (low level)",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040316475396866148/ezgif.com-gif-maker_2.gif",
            BeforeOpenSkill = "StaminaSkill4",
            AfterOpenSkills = "SwimingSkill2",
            AfterOpenSkills2 = "UnderWaterSkill1",
            SkillEffects = { A_SwimSpeed = 1.05 },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 37, -- in Nui Coords (%)

            iconName = "staminaskills3",  
        },
        {
            skill = "SwimingSkill2",
            skillName = "Aquaman : Chapter2",
            skillDescription = "Swim 1.15% faster on water (medium level)",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040316475396866148/ezgif.com-gif-maker_2.gif",
            BeforeOpenSkill = "SwimingSkill1",
            AfterOpenSkills = "SwimingSkill3",
            AfterOpenSkills2 = "",
            SkillEffects = { A_SwimSpeed = 1.15 },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 44, -- in Nui Coords (%)

            iconName = "staminaskills3",  
        },
        {
            skill = "SwimingSkill3",
            skillName = "Aquaman : Chapter3",
            skillDescription = "Swim 1.49% faster on water (high level)",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040316475396866148/ezgif.com-gif-maker_2.gif",
            BeforeOpenSkill = "SwimingSkill2",
            AfterOpenSkills = "",
            AfterOpenSkills2 = "",
            SkillEffects = { A_SwimSpeed = 1.49 },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 51, -- in Nui Coords (%)
            iconName = "staminaskills3",  
        },

        {
            skill = "UnderWaterSkill1",
            skillName = "Aquaman : Chapter4",
            skillDescription = "Under water you spend 20% less breath.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355521842130944/underwater.gif",
            BeforeOpenSkill = "SwimingSkill1",
            AfterOpenSkills = "UnderWaterSkill2",
            AfterOpenSkills2 = "",
            SkillEffects = { A_UnderwaterTime = 20,},
            marginTop = 32, -- in Nui Coords (%)
            marginLeft = 37, -- in Nui Coords (%)
            iconName = "staminaskills5",  
        },
        {
            skill = "UnderWaterSkill2",
            skillName = "Aquaman : Chapter5",
            skillDescription = "Under water you spend 30% less breath.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355521842130944/underwater.gif",
            BeforeOpenSkill = "UnderWaterSkill1",
            AfterOpenSkills = "UnderWaterSkill3",
            AfterOpenSkills2 = "",
            SkillEffects = { A_UnderwaterTime = 30, },
            marginTop = 36, -- in Nui Coords (%)
            marginLeft = 44, -- in Nui Coords (%)
            iconName = "staminaskills5",  
        },
        {
            skill = "UnderWaterSkill3",
            skillName = "Aquaman : Chapter6",
            skillDescription = "Under water you spend 40% less breath.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040355521842130944/underwater.gif",
            BeforeOpenSkill = "UnderWaterSkill2",
            AfterOpenSkills = "CarDrive1",
            AfterOpenSkills2 = "",
            SkillEffects = { A_UnderwaterTime = 40, },
            marginTop = 36, -- in Nui Coords (%)
            marginLeft = 53, -- in Nui Coords (%)
            iconName = "staminaskills5",  
        },

        -- Car Drive
        {
            skill = "CarDrive1",
            skillName = "The Driver : Chapter1",
            skillDescription = "5% more mph/km faster in your vehicle drive",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040353607398203515/vehiclegif.gif",
            BeforeOpenSkill = "UnderWaterSkill3",
            AfterOpenSkills = "CarDrive2",
            AfterOpenSkills2 = "",
            SkillEffects = { A_DriveSpeed = 5 },
            marginTop = 36, -- in Nui Coords (%)
            marginLeft = 61, -- in Nui Coords (%)
            iconName = "staminaskills4",  
        },
        {
            skill = "CarDrive2",
            skillName = "The Driver : Chapter2",
            skillDescription = "10% more mph/km faster in your vehicle drive",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040353607398203515/vehiclegif.gif",
            BeforeOpenSkill = "CarDrive1",
            AfterOpenSkills = "CarDrive3",
            AfterOpenSkills2 = "",
            SkillEffects = {  A_DriveSpeed = 10 },
            marginTop = 36, -- in Nui Coords (%)
            marginLeft = 68, -- in Nui Coords (%)
            iconName = "staminaskills4",  
        },
        {
            skill = "CarDrive3",
            skillName = "The Driver : Chapter3",
            skillDescription = "15% more mph/km faster in your vehicle drive",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040353607398203515/vehiclegif.gif",
            BeforeOpenSkill = "CarDrive2",
            AfterOpenSkills = "CarDrive4",
            AfterOpenSkills2 = "",
            SkillEffects = { A_DriveSpeed = 15 },
            marginTop = 36, -- in Nui Coords (%)
            marginLeft = 75, -- in Nui Coords (%)
            iconName = "staminaskills4",  
        },
        {
            skill = "CarDrive4",
            skillName = "The Driver : Chapter4",
            skillDescription = "20% more mph/km faster in your vehicle drive",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040353607398203515/vehiclegif.gif",
            BeforeOpenSkill = "CarDrive3",
            AfterOpenSkills = "BoatFaster1",
            AfterOpenSkills2 = "",
            SkillEffects = { A_DriveSpeed = 20 },
            marginTop = 36, -- in Nui Coords (%)
            marginLeft = 81, -- in Nui Coords (%)
            iconName = "staminaskills4",  
        },
        {
            skill = "BoatFaster1",
            skillName = "Technician : Chapter1",
            skillDescription = "Your boat goes 5% faster.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354349488017499/boatgif.gif",
            BeforeOpenSkill = "CarDrive4",
            AfterOpenSkills = "BoatFaster2",
            AfterOpenSkills2 = "",
            SkillEffects = { A_BoatSpeed = 5 },
            marginTop = 30, -- in Nui Coords (%)
            marginLeft = 81, -- in Nui Coords (%)
            iconName = "boatskill",  
        },
        {
            skill = "BoatFaster2",
            skillName = "Technician : Chapter2",
            skillDescription = "Your boat goes 10% faster.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354349488017499/boatgif.gif",
            BeforeOpenSkill = "BoatFaster1",
            AfterOpenSkills = "BoatFaster3",
            AfterOpenSkills2 = "",
            SkillEffects = { A_BoatSpeed = 10},
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 81, -- in Nui Coords (%)
            iconName = "boatskill",  
        },
        {
            skill = "BoatFaster3",
            skillName = "Technician : Chapter3",
            skillDescription = "Your boat goes 20% faster.",
            skillPoint = 2,
            skillGif = "https://cdn.discordapp.com/attachments/579140695072178236/1040354349488017499/boatgif.gif",
            BeforeOpenSkill = "BoatFaster2",
            AfterOpenSkills = "BoatFaster4",
            AfterOpenSkills2 = "",
            SkillEffects = { A_BoatSpeed = 20 },
            marginTop = 24, -- in Nui Coords (%)
            marginLeft = 88, -- in Nui Coords (%)
            iconName = "boatskill",  
        },
    },





    Text = {

       ["test"] = "Test message",
    },
}